collections:
  sections:
    output: false
  current_projects:
    output: false
  past_projects:
    output: false
  expertises:
    output: false

paginate: 7
paginate_path: "/blog/:num/"


plugins:
  - jekyll-paginate
