# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Ian Golden
tagline:             Entrepreneur. Developer. Artist.
url:                 http://iangolden.com
paginate:            3
baseurl:             ""
description:        The thoughts and ideas of Ian Golden. 
signoff:          "muan" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         Posts
    url:          /
    external:     false
  - name:         About me
    url:          /about
    external:     false

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ian Golden
  url:               https://iangolden.com
  email:             ian@iangolden.com

# Custom vars
version:             1.0.0
github:             igolden

gems: ['jekyll-paginate']
